### ISSUE TITLE
App crash while exploring app as new ser

### ISSUE THREAD

**Issue by IanDarwin** [ErfanRht/MovieLab#49]
**Describe the bug**
Stack trace in console when new user viewing the History page.

**To Reproduce**
0. Start with a clean install (never installed or removed, not just upgraded or restarted)
1. Go to  Lists
2. Go to Watchlist
3. Click on History

**Expected behavior**
Should see "empty box" graphic and "You havent added anything..." text. Should NOT see a stack trace in the console!

**Actual behaviour**

You do see the above graphic and text, but you also see this in the output from "flutter run":

An Observatory debugger and profiler on Pixel 6a is available at: http://127.0.0.1:49265/8Cq8jmHBJA4=/
The Flutter DevTools debugger and profiler on Pixel 6a is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:49265/8Cq8jmHBJA4=/
I/flutter (32039): All items of history deleted
E/flutter (32039): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/scroll_controller.dart': Failed assertion: line 107 pos 12: '_positions.isNotEmpty': ScrollController not attached to any scroll views.
E/flutter (32039): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (32039): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (32039): #2      ScrollController.position (package:flutter/src/widgets/scroll_controller.dart:107:12)
E/flutter (32039): #3      _UserListBodyState.initState.<anonymous closure>.<anonymous closure> (package:movielab/pages/shared/userlist_body.dart:44:37)
E/flutter (32039): #4      State.setState (package:flutter/src/widgets/framework.dart:1114:30)
E/flutter (32039): #5      _UserListBodyState.initState.<anonymous closure> (package:movielab/pages/shared/userlist_body.dart:42:28)
E/flutter (32039): <asynchronous suspension>
E/flutter (32039): 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser N/A

**Smartphone (please complete the following information):**
 - Device: Pixel 6A
 - OS: Android 13
 - Browser N/A

**Additional context**

**Comment by AlexHRodrii** [comment]
Can I work on it?

**Comment by ErfanRht** [comment]
@AlexHRodrii Sure, Go ahead!
I'll assign this to you

**Comment by felipecastrosales** [comment]
please, @AlexHRodrii :)
